version: "3.9"

name: laiiv-rag-chat

services:
  frontend:
    build: ./frontend
    command: ["uv", "run", "python", "main.py", "--server.port", "3000"]
    volumes: ["./frontend:/app"]
    ports:  ["3000:3000"]

  backend:
    build: ./RAG-chat
    command: ["uv", "run", "python", "main.py"]
    volumes: ["./RAG-chat:/app"]
    ports:  ["8000:8000"]
