name: laiiv-rag-chat

services:
  frontend:
    build: ./frontend
    ports:  ["3000:3000"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/


  backend:
    build: ./RAG-chat
    ports:  ["8000:8000"]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
