# base / production
services:

  pusher:
    container_name: laiive-pusher
    build: ./services/pusher
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USER: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}

  retriever:
    container_name: laiive-retriever
    build: ./services/retriever
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USER: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
