# base / production
services:
  frontend:
    container_name: laiive-frontend
    build: ./services/frontend
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      BACKEND_URL: http://backend:8000
      BACKEND_API_PATH: /chat

  backend:
    container_name: laiive-rag-chat-backend
    build: ./services/RAG-chat
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: >
        postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD} @${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

  db:
    container_name: laiive-postgres-db
    image: ankane/pgvector:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5433"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5

volumes:
  dbdata:
