services:
  frontend:
    container_name: laiive-rag-chat-frontend
    build: ./frontend
    command: ["uv","run","streamlit","run","main.py","--server.address","0.0.0.0","--server.port","3000"]
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/

  backend:
    container_name: laiive-rag-chat-backend
    build: ./RAG-chat
    command: ["uv","run","python","main.py","--server.port=8000"]
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
